### ISSUE TITLE
simple_command don't seem to work

### ISSUE THREAD

**Issue by winkleink** [google/aiyprojects-raspbian#14]
In action.py there are a number of simple_command.
For example 

simple_command('alexa', _("We've been friends since we were both starter projects"))

If I say Alexa I don't get the response shown above.

**Comment by drigz** [comment]
Currently all the `simple_command`s are just for the Cloud Speech API, since the Assistant has its own responses for these sorts of comments.

The website has [instructions to use the Cloud Speech](https://aiyprojects.withgoogle.com/voice/#makers-guide-3-1--change-to-the-cloud-speech-api), alternatively you could copy the `def simple_command` helper to below the comment `Add your own voice commands` and use it there.
