### ISSUE TITLE
hacking guide: Error trying to run /boot/check_audio.py

### ISSUE THREAD

**Issue by akramh** [google/aiyprojects-raspbian#280]
I am getting PermissionError: [Errno 13] Permission denied: '/boot/config.txt' -> '/boot/config.txt.bak' 

I already have virtualenv enabled this file seems to be inaccessible. Trying to comment that code generates even another error any one know what is going on why it is not working

**Comment by PaulFinch** [comment]
I had to use sudo with that script.

**Comment by akramh** [comment]
I did and it didn't work. It worked when i use python from virtualenv like this - sudo env/bin/python

**Comment by drigz** [comment]
Thanks for the report, @akramh! This is a known issue and a fix is on the way. In the short term, the workaround is to use:

`sudo env/bin/python checkpoints/check_audio.py`

as you discovered.

**Comment by hack-r** [comment]
Per the instructions you would've had the (env) virtual env loaded via the settings of the prescribed "dev terminal" configured in the AIY image, right? So that part is implicit I guess, that if you're using another terminal you need to load the env youself. So that being said its just a matter of sudo as @PaulFinch commented.

Incidentally is this still open or should it be closed?

**Comment by dmitriykovalev** [comment]
We are not using `virtualenv` anymore, everything should be working just by running `python3` directly.
