### ISSUE TITLE
Voice kit v1 with Pi Zero

### ISSUE THREAD

**Issue by mpember** [google/aiyprojects-raspbian#391]
With the new kit being released with a Pi0, is this change in compatibility due to a hardware change in the HAT?

Does the current code/API support using the original HAT with a Pi Zero W?

**Comment by dmitriykovalev** [comment]
Yes, original (v1) Voice Hat  should work on Pi Zero as well, just use our SD card image.

**Comment by mpember** [comment]
Does this mean that the limitation of hotword support was resolved?  Are there no functional limitations that result from using a Pi0?

**Comment by mpember** [comment]
@dmitriykovalev I have installed the official image.  Only the button trigger works. No sign of hotword trigger working.  Is there any special step required to get it working?

**Comment by dmitriykovalev** [comment]
That's correct. Unfortunately, Pi Zero is not powerful enough for real time hotword detection. We rely on assistant library which is optimized only for armv7l, i.e. for Pi 3, more info can found here: https://developers.google.com/assistant/sdk/overview

**Comment by mpember** [comment]
@dmitriykovalev 
Does this mean that v2 of the kit is less functional than v1?  Does the v2 image use a different API/SDK?

**Comment by dmitriykovalev** [comment]
No, that doesn't mean that. V2 board is more advanced than V1. The question is about Raspberry Pi board (Pi Zero vs Pi 3). We use the same software and the same Assistant library for both.

**Comment by mpember** [comment]
So, anyone who owns a v2 voicekit would need to replace the Pi0 (and the case) to get hotword functionality?  Am I wrong to consider the loss of hotword functionality a step backwards?

**Comment by PeterMalkin** [comment]
@mpember 
Not exactly.
Voice Hat v2 and Voice Hat v1 both work on either version of the raspberry pi. So users feel free to use either of the Hats with the raspberry pi of their choosing.
Raspberry pi 0 is not powerful enough to support hotwording. This is due to the fact that their CPU is only single core arm v6. AIY team cannot really do anything about it, therefore, if you want to use the hotwording feature you have to use raspberry pi 3 with your builds.

Hope this helps.
