### ISSUE TITLE
AIY Voice, accessibility request, send text inquiries

### ISSUE THREAD

**Issue by ztynzo** [google/aiyprojects-raspbian#428]
This may be a weird request, but... I'd like to be able to have my AIY kit respond with the time if it hears no audio (and haven't seen a way to do this yet).

I wear a CPAP mask to sleep, and have poor vision, so talking and seeing are not really great options when I wake up at night and wonder what time it is, however pressing a button, waiting a few seconds and listening... sounds really good.

**Comment by mpember** [comment]
If you are using a hotword trigger, you could simply ask 'hey google, what time is it?'.  Why is this not possible?

If you use hotword trigger, it would be possible to have a custom listener that monitors the button.  This would make it possible to have a custom action for when the button is pressed.

I have a slight variation of this.  When I am playing a podcast (or a streaming radio station), I attach a listener to make it possible to stop playback by pressing the button.  If the playback ends due to reaching the end of the podcast, the listener is removed.
