### ISSUE TITLE
longer short flex

### ISSUE THREAD

**Issue by wuhland** [google/aiyprojects-raspbian#434]
I would like to use the AIY vision setup in conjunction with another peripheral attached in between the Vision Bonnet and the RPi. Sadly the short flex is a wee bit short to accommodate this. Are there somewhat longer versions of this flex available anywhere?

**Comment by dmitriykovalev** [comment]
Any of these 22POS 0.5MM pitch FFC cables should work:

https://www.digikey.com/products/en/cable-assemblies/flat-flex-ribbon-jumper-cables/457?k=FFC&k=&pkeyword=FFC&pv1989=0&FV=1640055%2Cii22%7C2166%2Cffe001c9%2C40800d1&quantity=0&ColumnSort=0&page=1&pageSize=25

**Comment by andrewtvuong** [comment]
@dmitriykovalev Hi I am trying to use the Pi 3 B with the vision bonnet. Can you recommend a flex cable between the Pi 3 B and bonnet that has a short enough connector that it would fit? The USB ports are too close to the bonnet for the standard cables.

I even clipped the peeled hard black piece in half but it still seems too squished, may have shorted the board because it wouldn't even power on.

Thanks for any suggestions!
