### ISSUE TITLE
Compiler error: Not enough on-device memory to run model

### ISSUE THREAD

**Issue by Aileenlingyu** [google/aiyprojects-raspbian#436]
Hi, I am trying to compile my own model of which the frozen graph file is around 4.7MB, I use all the supported operations mentioned [here](https://aiyprojects.withgoogle.com/vision/#constraints), but got the error: Not enough on-device memory to run the model
![image](https://user-images.githubusercontent.com/22608026/43007946-ca9d33e6-8c07-11e8-80e2-b6535205b0d7.png)
Is it a problem with my model architecture? I am feeding the input tensor to three parallel sub-network, but in each sub-network, there are only a few layers. Is there any suggestion for me? Thanks a lot!

**Comment by weiran-work** [comment]
@Aileenlingyu 
The on-device memory has little to do with your frozen graph size. Having parallel sub-network cost a lot more on-device memory than a single 'tower' network structure, because internally, it needs to keep the unconsumed tensors from other subnetworks while working on one of the subnetwork.

I'm not sure what is your goal here, if you can achieve the same goal with a single tower network structure, it is more promising to deploy that on VisionKit. Or use 160x160 0.5 mobilenet structure, which is well supported. If that is too big for your application, you can try a smaller input size, like 128x128.
