### ISSUE TITLE
quota exceed

### ISSUE THREAD

**Issue by nunziofiore** [google/aiyprojects-raspbian#487]
Hi all, 
 I don't understand where can I set to use pay per use call when I have
"429 Client Error: Too Many Requests for url"
I understood that I overflow my 500 call for days but I'm in development and need a lot of more call.

I also upgraded my account to a pay per use account using also the free credit, but I don t see any difference and my scripts are all blocked with the same error. Someone can explain me better what I have to do?

**Comment by manoj7410** [comment]
@nunziofiore error 429 usually means that server is getting the spam requests. I am not sure about 500 calls limit because I am using the voice kit for last 4 months and never saw this on my kit. Only time I saw this error on voice kit, is this github issue : https://github.com/google/aiyprojects-raspbian/issues/472

Did you wait for a while and then tried again ? 

If you are trying to automatically send requests to your assistant then it is recommended to put a sleep call after every request.
