### ISSUE TITLE
Please, can you enable a kernel parameter for ADC (triggered sampling)?

### ISSUE THREAD

**Issue by dchichkov** [google/aiyprojects-raspbian#552]
I'd like to be able to trigger ADC by a HRES timer and read data buffered in kernel, not just user space reads from the device.  I think this option is available in the Industrial I/O, in the linux kernel config.  

```
  Device Drivers / 
    Industrial I/O support  /
      Enable software triggers support [y]
       *** Triggers - standalone ***
            High resolution timer trigger  [y]

```
 I was able to cross-build and run 4.14.90+ with this modification, it boots.  Was also able to re-build your DKMS modules, with "sudo apt-get install -y aiy-vision-dkms --reinstalls", but for some reason the aiy_vision doesn't come up, if I build kernel myself...:
```
[   19.637716] aiy_vision: loading out-of-tree module taints kernel.
[   19.639181] aiy-vision spi0.0: Initializing
[   19.842187] aiy-vision spi0.0: Failed to bind reset GPIO

```
I'd appreciate, if you could enable this option in the kernel - I think it makes sense to have it enabled in the industrial IO, so a bit more precise quantization for your awesome ADC is available.   Thanks!

**Comment by dmitriykovalev** [comment]
@dchichkov We build our image on top of https://www.raspberrypi.org/downloads/raspbian/, so you should probably ask them to enable that parameter in kernel config. 

Regarding `Failed to bind reset GPIO` -- that's because of driver init order, there are usually several of them. Check for `Myriad ready` message in the kernel log, it means everything is actually fine.
